1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

empty_array=np.empty((2,2))
print("Empty array (2x2):"+'\n',empty_array)

ones_array=np.ones((4,2))
print("All ones array (4x2):"+'\n',ones_array)

fill_value = 6
new_array = np.full((2, 2), fill_value)
print("Fill array (2x2):"+'\n',new_array)

zeros_array = np.zeros_like(new_array)
print("Zeros array (2x2):"+'\n',zeros_array)

ones_like_array = np.ones_like(new_array)
print("Ones array (2x2):"+'\n',ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy array from list:", numpy_array)

Empty array (2x2):
 [[0. 0.]
 [0. 0.]]
All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Fill array (2x2):
 [[6 6]
 [6 6]]
Zeros array (2x2):
 [[0 0]
 [0 0]]
Ones array (2x2):
 [[1 1]
 [1 1]]
Numpy array from list: [1 2 3 4]


 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}
 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [12]:
import numpy as np

res=np.arange( 10,50)
print("The ranging values from 10 to 49 are :")
print(res)

matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values ranging from 0 to 8:")
print(matrix_0_to_8)

identity_matrix = np.eye(3)
print("3x3 identity matrix:")
print(identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array of size 30:")
print(random_array)
print("Mean of the array:")
print(mean_value)

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 array with random values:")
print(random_10x10)
print("\nMinimum value in the array:")
print(min_value)
print("Maximum value in the array:")
print(max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array of size 10 with 5th element as 1:")
print(zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:")
print(reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on the border and 0 inside:")
print(border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 matrix with a checkerboard pattern:")
print(checkerboard)


The ranging values from 10 to 49 are :
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array of size 30:
[0.4258443  0.81266233 0.69448931 0.89903312 0.45919047 0.75707993
 0.7791958  0.74276456 0.80413406 0.9918488  0.23091323 0.48434434
 0.4263286  0.4140251  0.57071252 0.76039461 0.23894272 0.00491893
 0.14680008 0.89167332 0.95146709 0.50453882 0.88192322 0.32159456
 0.1514113  0.04792625 0.76884396 0.48305008 0.11367502 0.52918192]
Mean of the array:
0.542963611129956
10x10 array with random values:
[[0.43774132 0.71099721 0.51754888 0.05202773 0.43808888 0.54088935
  0.65206575 0.4085541  0.5999808  0.94389409]
 [0.78389035 0.54446657 0.82605142 0.10883622 0.43203627 0.78263186
  0.11817395 0.11018521 0.98031686 0.17400501]
 [0.84781298 0.42401369 0.3733871  0.13039423 0.

Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);

 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [3]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add = x + y
print("Addition of x and y:\n", add)

sub_xy = x - y
print("Subtraction of x and y:\n", sub_xy)

multiply_x = x * 2
print("Multiplication of x with 2:\n", multiply_x)

square_x = x ** 2
print("Square of each element in x:\n", square_x)

# Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n", concat_xy_row)

concat_vw_col = np.vstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error in concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]
Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]
Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT.

 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

In [22]:
import numpy as np

a = np.array([[3,4],[7,8]])
b = np.array([[5,3],[2,1]])

a_inv = np.linalg.inv(a)

result = np.dot(a, a_inv)
rounded_result = np.round(result, decimals=10)

identity_matrix = np.eye(a.shape[0])
print("A * A^-1:\n", rounded_result )
print("Is A * A^-1 equal to the identity matrix?", np.allclose(rounded_result , identity_matrix))


# Perform matrix multiplication AB and BA
a_dot_b = np.dot(a,b)
print("\nA * B:\n", a_dot_b)

b_dot_a = np.dot(b,a)
print(" B* A:\n", b_dot_a)

print("Is AB equal to BA?", np.array_equal(a_dot_b, b_dot_a))


a_Transpose =np.transpose(a)
b_Transpose =np.transpose(b)
aT_bT = np.dot(a_Transpose,b_Transpose)
print("\n(A^T) * (B^T):\n", aT_bT)

ab_Transpose =np.transpose(a_dot_b)
print("(AB)^T:\n",ab_Transpose)

print("Is (AB)^T equal to B^T A^T?",np.array_equal(aT_bT,ab_Transpose))


A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Solve for X using the inverse of A
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution X:\n", X)


A * A^-1:
 [[1. 0.]
 [0. 1.]]
Is A * A^-1 equal to the identity matrix? True

A * B:
 [[23 13]
 [51 29]]
 B* A:
 [[36 44]
 [13 16]]
Is AB equal to BA? False

(A^T) * (B^T):
 [[36 13]
 [44 16]]
(AB)^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T? False
Solution X:
 [ 2.  1. -2.]
